version: "3.7"

services:
  flaconi-cmd-app:
    build:
      context: cmd_app
      dockerfile: Dockerfile
      target: dev
    container_name: flaconi-cmd_app
#    restart: always
#    networks:
#      - flaconi
    volumes:
      - ./:/go/src/app
      - gopkg:/go/pkg

volumes:
  gopkg:
#
#networks:
#  flaconi:
#    driver: bridge
