version: "3.7"

services:
  flaconi-cmd-app:
    build:
      context: .
      dockerfile: containers/cmd/Dockerfile
    container_name: flaconi_cmd_app
    volumes:
      - .:/app
      - gopkg:/go/pkg
      - exclude:/app/docs

  flaconi-rest-app:
    build:
      context: .
      dockerfile: containers/api/Dockerfile
    container_name: flaconi_rest_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - gopkg:/go/pkg
      - exclude:/app/docs
    env_file: ./.env

volumes:
  gopkg:
  exclude:
